$raws="S01_off_hold"
SRC_REC_AFTER_SSS=0
SRC_REC_AFTER_SSP=0
SRC_REC_AFTER_ICA=0

RESAVE_BAD_CHANS_SSS=no
SRC_REC_BAD_CHANS_SSS=no

$INTERACTIVE=""
ipython3 $INTERACTIVE resave.py -- -r $raws --read_type "" --to_perform resample,notch
ipython3 $INTERACTIVE resave.py -- -r $raws --read_type resample,notch --to_perform highpass
ipython3 $INTERACTIVE resave.py -- -r $raws --read_type resample,notch --to_perform SSS,ICA --badchans_SSS $RESAVE_BAD_CHANS_SSS
ipython3 $INTERACTIVE resave.py -- -r $raws --read_type resample,notch --to_perform SSP,ICA
#ipython3 $INTERACTIVE resave.py -- -r $raws --read_type resample --to_perform SSS,ICA

#afterICA will have to be generated by hand

ipython3 $INTERACTIVE resave.py -- -r $raws --read_type "" --to_perform resample,notch,highpass


#. srun_prepSourceCoords.sh     -- better run separately for all subjects at once, since it is fast
#. batch_ftsrcr                 --  I need to pass parameters somehow
#. batch_process_FTsources.sh   --  I need to pass parameters somehow
