#!/bin/bash

#$raws="S01_off_hold"
#raw="S97_off_move"
#raw="S05_off_hold"
#raw="S05_off_move"
raw=$1

RESAVE_BAD_CHANS_SSS=no
SRC_REC_BAD_CHANS_SSS=no

#INTERACTIVE="-i"
INTERACTIVE=""

HIRES_FILE_TYPE=fieldtrip_raw

  RECALC_ARTIF0=0
  RECALC_ARTIF1=0
RESAVE_MAT_FILE=1
       HIGHPASS=1
       ICA_only=1
           tSSS=0
            SSP=0

   RECONSTRUCT_SOURCES=0
SRC_REC_AFTER_highpass=0
    SRC_REC_AFTER_tSSS=0
     SRC_REC_AFTER_SSP=0
     SRC_REC_AFTER_ICA=0
        RUN_MATLAB_JOB=0


# first pass, only artif plots to adjust artif detection alg params
# second pass, detect artif using updated params
#HIRES_FILE_TYPE=hires-raw
#HIRES_FILE_TYPE=fieldtrip_raw
#  RECALC_ARTIF0=0
#  #RECALC_ARTIF0=1
#  RECALC_ARTIF1=1
#       HIGHPASS=0
#       ICA_only=0
#           tSSS=0
#            SSP=0
#
#   RECONSTRUCT_SOURCES=0
#SRC_REC_AFTER_highpass=0
#    SRC_REC_AFTER_tSSS=0
#     SRC_REC_AFTER_SSP=0
#     SRC_REC_AFTER_ICA=0
#        RUN_MATLAB_JOB=0
#########################



MIN_DURATION_QUIET_ALLOWED=30
#MIN_DURATION_QUIET_ALLOWED=5  # for shorter test datasets

# DEBUG
RECALC_SRC_COORDS=1
MIN_DURATION_QUIET_ALLOWED=5  # for shorter test datasets
SRCREC_COVMAT_REST_ONLY=0
#SRCREC_COVMAT_REST_ONLY=1

RECALC_SRC_COORDS=0
# for matlab
ROI_TYPES='"'parcel_aal_surf'"' 
#ROI_TYPES='"'HirschPt2011,2013'"'
# for process_FTsources 
ROI_TYPES2=parcel_aal_surf  
MEG_artif_types='MEGartif,MEGartif_muscle,MEGartif_ICA'

# for sources extraction
GROUPINGS="all_raw"
ALG_TYPE='all_sources'

RUNDIR=$OSCBAGDIS_DATAPROC_CODE/run
RUNF=$RUNDIR/resave.py

if [ $RECALC_ARTIF0 -ne 0 ]; then
  python $INTERACTIVE $RUNF -r $raw --read_type $HIRES_FILE_TYPE --to_perform notch --exit_after MEG_artif_calc --recalc_artif 1 --recalc_LFPEMG 0 --force_artif_ICA_recalc 1  load_artif_detection_params 0
  EC=$?
  if [ $EC -ne 0 ]; then
    echo "Exit code $EC, exiting"
    exit $EC
  fi
fi

if [ $RECALC_ARTIF1 -ne 0 ]; then
  python $INTERACTIVE $RUNF -r $raw --read_type $HIRES_FILE_TYPE --to_perform notch --exit_after MEG_artif_calc --recalc_artif 1 --recalc_LFPEMG 0 --force_artif_ICA_recalc 0   load_artif_detection_params 1 
  EC=$?
  if [ $EC -ne 0 ]; then
    echo "Exit code $EC, exiting"
    exit $EC
  fi
fi

if [ $RESAVE_MAT_FILE -ne 0 ]; then
  python $INTERACTIVE $RUNF -r $raw --read_type $HIRES_FILE_TYPE --to_perform resample,notch --recalc_artif 0 --recalc_LFPEMG 0
  EC=$?
  if [ $EC -ne 0 ]; then
    echo "Exit code $EC, exiting"
    exit $EC
  fi
fi

#DEBUG

if [ $HIGHPASS -ne 0 ]; then
  python $INTERACTIVE $RUNF -r $raw --read_type resample,notch --to_perform highpass  --recalc_artif 0 --recalc_LFPEMG 0
  EC=$?
  if [ $EC -ne 0 ]; then
    echo "Exit code $EC, exiting"
    exit $EC
  fi
fi

if [ $ICA_only -ne 0 ]; then
  python $INTERACTIVE $RUNF -r $raw --read_type $HIRES_FILE_TYPE --to_perform ICA --recalc_LFPEMG 0 --recalc_artif 0 
  EC=$?
  if [ $EC -ne 0 ]; then
    echo "Exit code $EC, exiting"
    exit $EC
  fi
fi

if [ $tSSS -ne 0 ]; then
  #python $INTERACTIVE $RUNF -r $raw --read_type resample,notch --to_perform tSSS,ICA --badchans_SSS $RESAVE_BAD_CHANS_SSS
  python $INTERACTIVE $RUNF -r $raw --read_type $HIRES_FILE_TYPE --to_perform tSSS,ICA --badchans_SSS $RESAVE_BAD_CHANS_SSS --output_subdir SSS --recalc_LFPEMG 0 --recalc_artif 0 
  EC=$?
  if [ $EC -ne 0 ]; then
    echo "Exit code $EC, exiting"
    exit $EC
  fi
fi
if [ $SSP -ne 0 ]; then
  python $INTERACTIVE $RUNF -r $raw --read_type resample,notch --to_perform SSP,ICA --output_subdir SSP --recalc_artif 0
  EC=$?
  if [ $EC -ne 0 ]; then
    echo "Exit code $EC, exiting"
    exit $EC
  fi
fi
#python $INTERACTIVE $RUNF -r $raw --read_type resample --to_perform tSSS,ICA

#afterICA will have to be generated by hand

#python $INTERACTIVE $RUNF -r $raw --read_type $HIRES_FILE_TYPE --to_perform resample,notch,highpass


#S98_modcoord_parcel_aal.mat
#headmodel_grid_S01.mat       
#headmodel_grid_S01_surf.mat

#OUTPUT_SUBDIR=highpass_covmat_rest

MATLAB_SCRIPT_PARAMS_DEF=""
MATLAB_SCRIPT_PARAMS_DEF=$MATLAB_SCRIPT_PARAMS_DEF'roi = {'$ROI_TYPES'};'
#MATLAB_SCRIPT_PARAMS_DEF=$MATLAB_SCRIPT_PARAMS_DEF'input_rawname_type = ["resample", "notch", "highpass"];'

if [ $RECONSTRUCT_SOURCES -ne 0 ]; then
  if [ $RECALC_SRC_COORDS -ne 0 ]; then
      #better run separately for all subjects at once, since it is fast 
    . srun_prepSourceCoords.sh    
  fi

  ## if [ $SRCREC_COVMAT_REST_ONLY -ne 0 ]; then
  ##   s="--ann_types $MEG_artif_types,beh_states"
  ## else
  ##   s="--ann_types $MEG_artif_types"
  ## fi
  ## python $OSCBAGDIS_DATAPROC_CODE/run/run_collect_artifacts.py -r $raw --min_dur $MIN_DURATION_QUIET_ALLOWED $s
  ## EC=$?
  ## if [ $EC -ne 0 ]; then
  ##   echo "run_resave_resample.sh: Exit code $EC, exiting"
  ##   exit $EC
  ## fi

  # this way for single file only 
  if [ $SRC_REC_AFTER_highpass -ne 0 ]; then
    if [ $RUN_MATLAB_JOB -ne 0 ]; then
      MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS_DEF
      MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS'input_rawname_type = ["resample", "notch", "highpass"];'
      MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS"use_data_afterICA=0;"
      if [ -z ${OUTPUT_SUBDIR+x} ]; then
        echo "undef OUTPUT_SUBDIR"
      else
        MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS'output_subdir="'$OUTPUT_SUBDIR'";'
      fi
      . $RUNDIR/srun_Fieldtrip_srcrec.sh $raw
      if [ $EC -ne 0 ]; then
        echo "Exit code $EC, exiting"
        exit $EC
      fi
    fi

    python $INTERACTIVE $RUNDIR/run_process_FTsources.py -r $raw --groupings $GROUPINGS --alg_type $ALG_TYPE --sources_type $ROI_TYPES2
  fi
  if [ $SRC_REC_AFTER_tSSS -ne 0 ]; then
    if [ $RUN_MATLAB_JOB -ne 0 ]; then
      MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS_DEF

      if [ -z ${OUTPUT_SUBDIR+x} ]; then
        echo "undef OUTPUT_SUBDIR, setting to SSS"
        OUTPUT_SUBDIR=SSS
        MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS'output_subdir="'$OUTPUT_SUBDIR'";'
      fi

      if [ -z ${INPUT_SUBDIR+x} ]; then
        echo "undef INPUT_SUBDIR, setting to SSS"
        INPUT_SUBDIR=SSS
        MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS'input_subdir="'$INPUT_SUBDIR'";'
      fi
      MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS"use_data_afterICA=0;"
      MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS'input_rawname_type=["SSS",  "notch", "highpass", "resample"];'
      . $RUNDIR/srun_Fieldtrip_srcrec.sh $raw
      if [ $EC -ne 0 ]; then
        echo "Exit code $EC, exiting"
        exit $EC
      fi

      #S='input_rawname_type=["SSS",  "notch", "highpass", "resample"]; input_subdir="SSS"; output_subdir="SSS"; '  
    fi

    python $INTERACTIVE $RUNDIR/run_process_FTsources.py -r $raw --groupings $GROUPINGS --alg_type $ALG_TYPE --input_subdir SSS --output_subdir SSS
    EC=$?
    if [ $EC -ne 0 ]; then
      echo "Exit code $EC, exiting"
      exit $EC
    fi
  fi
  if [ $SRC_REC_AFTER_ICA -ne 0 ]; then
    if [ $RUN_MATLAB_JOB -ne 0 ]; then
      MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS_DEF
      MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS"use_data_afterICA=1;"
      MATLAB_SCRIPT_PARAMS=$MATLAB_SCRIPT_PARAMS'input_rawname_type = ["resample", "notch", "highpass"];'
      . $RUNDIR/srun_Fieldtrip_srcrec.sh $raw
      if [ $EC -ne 0 ]; then
        echo "Exit code $EC, exiting"
        exit $EC
      fi
    fi

    python $INTERACTIVE $RUNDIR/run_process_FTsources.py -r $raw --groupings $GROUPINGS --alg_type $ALG_TYPE --input_subdir afterICA --output_subdir afterICA
    EC=$?
    if [ $EC -ne 0 ]; then
      echo "Exit code $EC, exiting"
      exit $EC
    fi
  fi
fi

